# Dynamic Proxy Configuration File

[server]
tcp_bind = "0.0.0.0:8080"
udp_bind = "0.0.0.0:8081"
worker_threads = 4
max_connections = 10000
connection_timeout = 30  # seconds
buffer_size = 8192

[redis]
url = "redis://localhost:6379"
password = "Qwert12345"
db = 0
pool_size = 10
connection_timeout = 5  # seconds
command_timeout = 3     # seconds

[logging]
level = "info"
format = "pretty"  # "json" or "pretty"
# file = "/var/log/dynamic-proxy.log"
max_size = 100  # MB
max_files = 10

[metrics]
enabled = true
bind = "0.0.0.0:9090"
path = "/metrics"
collect_interval = 10  # seconds

[health_check]
enabled = true
interval = 30      # seconds
timeout = 5        # seconds
retries = 3
failure_threshold = 3
success_threshold = 2

# Router configurations
[routers.round_robin]
plugin = "round_robin"
config = {}

[routers.weighted]
plugin = "weighted"
config = { smooth_weighted = true }

[routers.hash_ip]
plugin = "hash"
config = { hash_key = "client_ip" }

[routers.least_conn]
plugin = "least_connections"
config = {}

[routers.random]
plugin = "random"
config = {}

# Routing rules
[[rules]]
name = "web_traffic"
protocol = "tcp"
enabled = true
router = "round_robin"

[[rules.backends]]
id = "web_server_1"
name = "web_server_1"
address = "10.20.100.12:12087"
weight = 100
health_check = true
enabled = true

[rules.matcher]
type = "port"
port = 8080


